### PR TITLE
replaces XML request with fetch

### PR DESCRIPTION
**Pull request by MarissaLZ**

### CODE REVIEW

**Comment by ericabasak** [comment]
Good job!

**Comment by MarissaLZ** [comment]
> 

I just did my website presentation last week, so I’m excited to have finished!

**Comment by ericabasak** [comment]
Congratulations Marissa! You have an exciting journey ahead :)

Did you create a demo/video of your presentation? I'd love to see it

**Comment by MarissaLZ** [comment]
Oh no I’m sorry I don’t have a recorded demo. They had us present it live
to everyone. I am going to publish it on GitHub this week. I’ll send you a
link as soon as it’s up!

**Comment by MarissaLZ** [comment]
I found out they recorded the live presentations. Here’s a link! I was the
first presenter up.

https://youtu.be/f6W8m3Q1Y9U

**Comment by ericabasak** [comment]
Great! Thanks for sharing the video - nice work!

**Pull request merged**
